import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.KILO_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
	? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
	: await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
const snapshot = JSON.parse(modelsData)
if (snapshot.kilo) {
	snapshot.kilo.name = "Zoo Code Gateway"
	const models = snapshot.kilo.models ?? {}
	if (models["kilo-auto/balanced"]) models["kilo-auto/balanced"].name = "Zoo Code Auto Balanced"
	if (models["kilo-auto/frontier"]) models["kilo-auto/frontier"].name = "Zoo Code Auto Frontier"
	if (models["kilo-auto/small"]) models["kilo-auto/small"].name = "Zoo Code Auto Small"
	if (models["kilo-auto/free"]) models["kilo-auto/free"].name = "Zoo Code Auto Free"
}
await Bun.write(
	path.join(dir, "src/provider/models-snapshot.js"),
	`// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(snapshot)}\n`,
)
await Bun.write(
	path.join(dir, "src/provider/models-snapshot.d.ts"),
	`// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
